
CREATE TABLE HOURLY_RATE
(HID VARCHAR(20) NOT Null,
 RATE DECIMAL(10,2),
 PRIMARY KEY (HID));
 
CREATE TABLE BUILDING
(BID VARCHAR(20) NOT NULL,
 NAME VARCHAR(30),
 TYPE VARCHAR(30),
 PRIMARY KEY(BID)
);

CREATE TABLE ENCLOSURE
(BID VARCHAR(20),
 EN_ID VARCHAR(20),
 SQFT DECIMAL(5,2),
 PRIMARY KEY (BID,EN_ID),
 CONSTRAINT enclosure_fk_bid FOREIGN KEY (BID) REFERENCES BUILDING(BID)
);
 
CREATE TABLE REVENUE_TYPE
(RID VARCHAR(20) NOT NULL,
 NAME VARCHAR(30),
 TYPE VARCHAR(25),
 BID VARCHAR(20) NOT NULL,
 PRIMARY KEY (RID),
 CONSTRAINT revenue_fk_bid FOREIGN KEY (BID) REFERENCES BUILDING(BID)
);

CREATE TABLE REVENUE_EVENTS
(RID VARCHAR(20) NOT NULL,
 DATE_TIME DATE NOT NULL,
 REVENUE DECIMAL(10,2),
 TICKETS_SOLD INT,
 PRIMARY KEY (RID,DATE_TIME),
 CONSTRAINT re_fk_revenue FOREIGN KEY (RID) REFERENCES REVENUE_TYPE(RID)
);

CREATE TABLE ZOO_ADMISSION
(RID VARCHAR(20) NOT NULL,
 SENIOR_PRICE DECIMAL(5,2),
 ADULT_PRICE DECIMAL(5,2),
 CHILD_PRICE DECIMAL(5,2),
 PRIMARY KEY (RID),
 CONSTRAINT zoo_fk_revenue FOREIGN KEY (RID) REFERENCES REVENUE_TYPE(RID)
);

CREATE TABLE CONCESSION
(RID VARCHAR(20) NOT NULL,
 PRODUCT VARCHAR(30),
 PRIMARY KEY (RID),
 CONSTRAINT concession_fk_revenue FOREIGN KEY (RID) REFERENCES REVENUE_TYPE(RID)
);
 
CREATE TABLE EMPLOYEE
(EID VARCHAR(20) NOT Null,
 STARTDATE DATE,
 JOBTYPE VARCHAR(20),
 FIRST VARCHAR(25),
 MINIT VARCHAR(25),
 LAST VARCHAR(25),
 STREET VARCHAR(30),
 CITY VARCHAR(30),
 STATE VARCHAR(30),
 ZIP NUMBER,
 SUPER_ID VARCHAR(20),
 HID VARCHAR(20),
 RID VARCHAR(20),
 PRIMARY KEY (EID),
 CONSTRAINT emp_fk_eid FOREIGN KEY (SUPER_ID) REFERENCES EMPLOYEE(EID),
 CONSTRAINT emp_fk_rate FOREIGN KEY (HID) REFERENCES HOURLY_RATE(HID),
 CONSTRAINT emp_fk_revenue FOREIGN KEY (RID) REFERENCES REVENUE_TYPE(RID)
);

CREATE TABLE SPECIES
(SID VARCHAR(20) NOT NULL,
 FOODCOST DECIMAL(10,2),
 NAME VARCHAR(20),
 PRIMARY KEY (SID)
);

CREATE TABLE ANIMAL
(AID VARCHAR(20) NOT NULL,
 STATUS VARCHAR(25),
 BIRTHYEAR VARCHAR(4),
 SID VARCHAR(20),
 BID VARCHAR(20),
 EN_ID VARCHAR(20),
 PRIMARY KEY (AID),
 CONSTRAINT animal_fk_sid FOREIGN KEY (SID) REFERENCES SPECIES(SID),
 CONSTRAINT animal_fk_enc FOREIGN KEY (BID,EN_ID) REFERENCES ENCLOSURE(BID,EN_ID)
);

CREATE TABLE ANIMAL_SHOWS
(RID VARCHAR(20) NOT NULL,
 SENIOR_PRICE DECIMAL(5,2),
 ADULT_PRICE DECIMAL(5,2),
 CHILD_PRICE DECIMAL(5,2),
 NO_PER_DAY INT,
 PRIMARY KEY (RID),
 CONSTRAINT animal_shows_fk_revenue FOREIGN KEY (RID) REFERENCES REVENUE_TYPE(RID)
);

CREATE TABLE PARTICIPATES_IN
(RID VARCHAR(20) NOT NULL,
 SID VARCHAR(20) NOT NULL,
 NO_REQD INT,
 CONSTRAINT participate_fk_show FOREIGN KEY (RID) REFERENCES ANIMAL_SHOWS(RID),
 CONSTRAINT participate_fk_species FOREIGN KEY (SID) REFERENCES SPECIES(SID)
);

CREATE TABLE CARES_FOR
(EID VARCHAR(20) NOT NULL,
 SID VARCHAR(20) NOT NULL,
 CONSTRAINT cares_fk_emp FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID),
 CONSTRAINT cares_fk_species FOREIGN KEY (SID) REFERENCES SPECIES(SID)
);

COMMIT;
